### ISSUE TITLE
未能找到自定义的 models 模块，导致 ImportError: Failed to import models

### ISSUE THREAD

**Issue by wangqingl** [yeliudev/CATNet#15]
你好我遇到了如下错误
`Training command is /home/WQL/anaconda3/envs/catnet/bin/python /home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmdet/.mim/tools/train.py /home/WQL/project/project/CATNet-main/configs/vhr/cat_mask_rcnn_r50_6x_vhr.py --launcher none.
Traceback (most recent call last):
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
                   ^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmengine/config/config.py", line 182, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import models

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmdet/.mim/tools/train.py", line 133, in <module>
    main()
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmdet/.mim/tools/train.py", line 70, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmengine/config/config.py", line 192, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['models', 'datasets']}, the current sys.path is:
    /home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmdet/.mim/tools
    /home/WQL/project/whl_list/home/WQL/project/project/CATNet-main
    /home/WQL/project/whl_list
    /home/WQL/anaconda3/envs/catnet/lib/python311.zip
    /home/WQL/anaconda3/envs/catnet/lib/python3.11
    /home/WQL/anaconda3/envs/catnet/lib/python3.11/lib-dynload
    /home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages
    /tmp/tmp8o25pg5w
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
Traceback (most recent call last):
  File "/home/WQL/anaconda3/envs/catnet/bin/mim", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mim/commands/train.py", line 100, in cli
    is_success, msg = train(
                      ^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mim/commands/train.py", line 261, in train
    ret = subprocess.check_call(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WQL/anaconda3/envs/catnet/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/WQL/anaconda3/envs/catnet/bin/python', '/home/WQL/anaconda3/envs/catnet/lib/python3.11/site-packages/mmdet/.mim/tools/train.py', '/home/WQL/project/project/CATNet-main/configs/vhr/cat_mask_rcnn_r50_6x_vhr.py', '--launcher', 'none']' returned non-zero exit status 1.
`
chatgpt解读如下：
从错误日志来看，主要问题在于你的代码未能找到自定义的 models 模块，导致 ImportError: Failed to import models。这意味着 Python 没有找到你自定义的模块，通常是因为 PYTHONPATH 中未包含包含该模块的目录。
我没有找到解决方案

**Comment by yeliudev** [comment]
Run `export PYTHONPATH=$PWD:$PYTHONPATH` before training.

**Comment by Tsing-time** [comment]
你好，请问你解决了吗

**Comment by wangqingl** [comment]
> 你好，请问你解决了吗

用上面这个方法就可以解决这个问题
![image](https://github.com/user-attachments/assets/103e9de1-b43b-4b38-9108-cdfd4f65819e)

**Comment by wangqingl** [comment]
> Run `export PYTHONPATH=$PWD:$PYTHONPATH` before training.

Thank you,man!!!Great job,man
