### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by talhayaseen57** [yeliudev/CATNet#7]
I am trying to test the model using given command:
`torchrun --nproc_per_node=4 tools/test.py <path-to-config> <path-to-checkpoint>`

I got the following error:
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/cta/users/******/CATNet/tools/test.py", line 12, in <module>
Traceback (most recent call last):
  File "/cta/users/******/CATNet/tools/test.py", line 12, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from mmcv.ops import RoIPool
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    from .assign_score_withk import assign_score_withk
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/importlib/__init__.py", line 126, in import_module
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
            return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mmcv._ext'
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mmcv._ext'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 478253) of binary: /cta/users/******/.conda/envs/catnet-env/bin/python3.11
Traceback (most recent call last):
  File "/cta/users/******/.conda/envs/catnet-env/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/******/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-25_00:10:58
  host      : nova32
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 478254)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-25_00:10:58
  host      : nova32
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 478253)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

How can I sort out the mmcv._ext module error? 
Following are the versions of the packages:
- mmcv-full=1.3.18

I even tried with the lite version of mmcv==1.3.17 but got the same error. Also I searched for this error on different platforms it was mentioned to uninstall previous versions and try to install latest version, but then got the incompatibility error about versions as mentioned in requirements.txt file.

**Comment by yeliudev** [comment]
Please try to install `mmcv-full` instead of `mmcv`.

**Comment by talhayaseen57** [comment]
I fixed the error using command:
`mim install mmcv-full`

**Comment by talhayaseen57** [comment]
Unfortunately later I encountered another error:
```
loading annotations into memory...
Done (t=4.27s)
creating index...
index created!
[                                                  ] 0/11752, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/cta/users/skoles/CATNet/tools/test.py", line 69, in <module>
    main()
  File "/cta/users/skoles/CATNet/tools/test.py", line 55, in main
    results = single_gpu_test(model, data_loader)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/apis/test.py", line 28, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/detectors/two_stage.py", line 179, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 130, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 93, in get_bboxes
    results = self._get_bboxes_single(cls_score_list, bbox_pred_list,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 185, in _get_bboxes_single
    return self._bbox_post_process(mlvl_scores, mlvl_bbox_preds,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 232, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/.conda/envs/catnet-env/lib/python3.11/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cta/users/skoles/CATNet/mmcv/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
           ^^^^^^^^^^^^^^^
RuntimeError: nms is not compiled with GPU support
```

**Comment by yeliudev** [comment]
It seems like a mmcv related problem. Please double-check whether you've compiled mmcv with CUDA, as the NMS requires CUDA support.

**Comment by talhayaseen57** [comment]
I verified mmcv installation and got following results:

`{'sys.platform': 'linux', 'Python': '3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]', 'CUDA available': True, 'GPU 0': 'NVIDIA RTX A6000', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Build cuda_12.0.r12.0/compiler.32267302_0', 'GCC': 'gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0', 'PyTorch': '2.0.0+cu117', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.7\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.5\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n', 'TorchVision': '0.15.1+cu117', 'OpenCV': '4.7.0', 'MMCV': '1.3.17', 'MMCV Compiler': 'GCC 11.3', 'MMCV CUDA Compiler': 'not available'}`

I noticed 'MMCV CUDA Compiler': 'not available'. Since I am working on slurm, therefore, I have requested my administrator to install CUDA 10.2. Maybe it will work.
